#!/bin/bash

# This is a thin wrapper around bitcredit-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using bitcredit-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_BITCREDITD

# Grab the value of $REAL_BITCREDITCLI which may be bitcredit-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_BITCREDITCLI}" "$@" | sed 's/\r//'
